// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhrRLQwBZwzVwlFPkjHNJuZbMUPDQLiw',
    appId: '1:86077023741:web:f43d35786d91d286c86594',
    messagingSenderId: '86077023741',
    projectId: 'stu-rsa',
    authDomain: 'stu-rsa.firebaseapp.com',
    storageBucket: 'stu-rsa.firebasestorage.app',
    measurementId: 'G-V3VL1WS6HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkNqRjHoZcYpZfzOjNSKF4w4Zkyt_g9Y',
    appId: '1:86077023741:android:4bc933716b18f2d3c86594',
    messagingSenderId: '86077023741',
    projectId: 'stu-rsa',
    storageBucket: 'stu-rsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1OOsfN91SqTSRCWBrNzFu2QZZA1nqdg',
    appId: '1:86077023741:ios:b1f689c0741c4630c86594',
    messagingSenderId: '86077023741',
    projectId: 'stu-rsa',
    storageBucket: 'stu-rsa.firebasestorage.app',
    iosBundleId: 'com.example.stdRideShare',
  );
}
